# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predmet',
            fields=[
                ('predmet_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('predmet_name', models.CharField(max_length=100)),
                ('predmet_category', models.CharField(default=b'razno', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('profesor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prostor',
            fields=[
                ('prostor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prostor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('skupina_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('skupina_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urnik_name', models.CharField(max_length=100)),
            ],
        ),
    ]
