# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('class_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('class_category', models.CharField(default='RAZNO', max_length=10)),
            ],
        ),
    ]
