# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20161215_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('profesor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('profesor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prostor',
            fields=[
                ('prostor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('prostor_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('skupina_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('skupina_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Urnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urnik_name', models.CharField(max_length=100)),
            ],
        ),
    ]
