# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(default=63279, on_delete=django.db.models.deletion.CASCADE, to='classes.Predmet'),
            preserve_default=False,
        ),
    ]
