# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('trznica', '0002_ponudbastudenta_studentwish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponudbastudenta',
            name='studentId',
        ),
        migrations.AddField(
            model_name='ponudbastudenta',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
