# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trznica', '0005_auto_20161230_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponudbastudenta',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
