# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', null=True, upload_to='profile_pic/', width_field='logo_width'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo_height',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='logo_width',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
